commerce_payment.commerce_payment_gateway.plugin.remibit_redirect_checkout:
  type: commerce_payment_gateway_configuration
  mapping:
    login_id:
      type: string
      label: 'Login ID'
    transaction_key:
      type: string
      label: 'Transaction key'
    signature_key:
      type: string
      label: 'Signature key'
    md5_hash:
      type: string
      label: 'MD5 Hash Value'
    gateway_url:
      type: string
      label: 'Endpoint URL'
